Add checkpoint eraser
wingman-ai/ray pull request #9
Opened 2019-03-12 15:59 UTC by dulex123

## What do these changes do?

## Related issue number

2019-03-12 16:21 UTC, nikola-j approved these changes

2019-03-13 10:19 UTC, bjg2 requested changes

2019-03-13 10:19 UTC, bjg2 commented on python/ray/rllib/agents/agent.py
> +    "keep_checkpoints": 30,
move these to tune, where `checkpoint_freq` is. Follow the path that argument is going. Your arguments should be able to be used from CLI as well.

2019-03-13 10:19 UTC, bjg2 commented on python/ray/rllib/agents/agent.py
> +    "keep_best_checkpoints": 30,
Both your arguments should not change current behavior - default them to None

2019-03-13 10:19 UTC, bjg2 commented on python/ray/tune/trainable.py
> +    def _delete(self, checkpoint_dir):
Rename _delete to delete_checkpoint, as it will be used from tune

2019-03-13 10:19 UTC, bjg2 commented on python/ray/tune/trainable.py
> +    def _checkpoint_high_reward(self, checkpoint_dir):
Move everything except delete_checkpoint to tune, probably somewhere in `ray_trial_executor.py`

2019-03-15 13:59 UTC, closed without merging